[features]
seeds = false
skip-lint = false
[programs.localnet]
calculator = "HQJcnHze1erzHaJATrYuMSGF9B7y1YHqoFxA3behTeb4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/tesh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
